name: Update remote
description: Update remote files
author: Dencer
env:
  CURSEFORGE_API_KEY:
    description: Curseforge api key
    required: true
inputs:
  token:
    description: 'Github token'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'index.js'
branding:
  color: 'blue'
  icon: 'play'
